"""empty message

Revision ID: 41058e032b2e
Revises: 47ee7cfd1e69
Create Date: 2022-08-12 03:20:44.990727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41058e032b2e'
down_revision = '47ee7cfd1e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_people', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_people', 'id')
    # ### end Alembic commands ###
