"""empty message

Revision ID: 455ce1bc15fb
Revises: 
Create Date: 2022-08-09 13:47:40.354760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455ce1bc15fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('people_name', sa.String(length=250), nullable=False),
    sa.Column('people_url', sa.String(length=250), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.Column('hair_color', sa.String(length=250), nullable=True),
    sa.Column('skin_color', sa.String(length=250), nullable=True),
    sa.Column('eye_color', sa.String(length=250), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=250), nullable=True),
    sa.Column('created', sa.String(length=250), nullable=True),
    sa.Column('edited', sa.String(length=250), nullable=True),
    sa.Column('homeworld', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('people_id'),
    sa.UniqueConstraint('people_name'),
    sa.UniqueConstraint('people_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=80), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('user_password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_name'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('favorite_people',
    sa.Column('own_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.people_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('own_id')
    )
    op.create_table('tags',
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.people_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('people_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('favorite_people')
    op.drop_table('users')
    op.drop_table('people')
    # ### end Alembic commands ###
