"""empty message

Revision ID: a64078d8ca78
Revises: b5cb99c659c5
Create Date: 2022-08-10 20:28:09.160077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a64078d8ca78'
down_revision = 'b5cb99c659c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_people', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_people', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
