"""empty message

Revision ID: b5cb99c659c5
Revises: 7f87dde55592
Create Date: 2022-08-10 20:25:03.982280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cb99c659c5'
down_revision = '7f87dde55592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_people', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_people', 'id')
    # ### end Alembic commands ###
