"""empty message

Revision ID: f86dfe871750
Revises: 455ce1bc15fb
Create Date: 2022-08-09 14:40:21.602648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f86dfe871750'
down_revision = '455ce1bc15fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_people',
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.people_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('people_id', 'user_id')
    )
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('people_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.people_id'], name='tags_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='tags_ibfk_2'),
    sa.PrimaryKeyConstraint('people_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_people')
    # ### end Alembic commands ###
